# Generated by Django 4.0.3 on 2022-06-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_useraespassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraespassword',
            old_name='AESpassword',
            new_name='aespassword',
        ),
    ]
