# Generated by Django 3.2.12 on 2022-03-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_nodes_node'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Node',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
