# Generated by Django 4.0.3 on 2022-06-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_aespassword_useraespassword_aespassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraespassword',
            old_name='aespassword',
            new_name='aes_password',
        ),
    ]
