# Generated by Django 3.2.12 on 2022-04-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_authinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authinformation',
            options={'verbose_name': 'Key', 'verbose_name_plural': 'Keys'},
        ),
    ]
