# Generated by Django 4.0.3 on 2022-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_aespassword_useraespassword_aes_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aes_pass',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
