# Generated by Django 3.2.12 on 2022-04-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_authinformation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authinformation',
            options={},
        ),
    ]
