# Generated by Django 4.0.3 on 2022-06-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_aes_pass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAESPassword',
        ),
    ]
