### Get headers

GET http://0.0.0.0:10002/api/headers?user_uuid=b545d618-ff44-4319-9c88-2100d9928f32
Accept: application/json

### Get notes by user

GET http://0.0.0.0:10002/api/notes?user_uuid=b545d618-ff44-4319-9c88-2100d9928f32
Accept: application/json

### Get note

GET http://0.0.0.0:10002/api/notes/9a7820d718fc65a5f02b139687eee516
Accept: application/json

### Create note

POST http://0.0.0.0:10002/api/notes
Content-Type: application/json

{
  "header": "header third",
  "body": "Hellow, this is my second note in BIPBIPVRUUM!",
  "user_uuid": "b545d618-ff44-4319-9c88-2100d9928f32"
}

### Update note
PATCH http://0.0.0.0:10002/api/notes/9a7820d718fc65a5f02b139687eee516
Content-Type: application/json

{
  "header": "update header",
  "body": "Hellow, this is update body "
}

### Delete note

DELETE http://0.0.0.0:10002/api/notes/564ff2b6de1909b2633a0561f892b2d7
Content-Type: application/json